# -*- coding: utf-8 -*-
# vim: ft=sls
#
# Every Salt Jinja filter, one test.nop state each -- open with the rendered
# preview (Ctrl+K V) with saltSyntax.saltVersion set to 3008.
# The 3006 (LTS) version of this file is salt_filters_3006.sls -- it lacks
# to_entries / from_entries, which 3006 doesn't have.
# `# ->` is the filter's own output as
# printed by Jinja -- generated by rendering each line, with the preview's filters
# verified against Salt's own implementations (test/salt-filter-parity.test.py).
# `- result:` wraps it in `| tojson` so the file stays valid YAML whatever it returns.
# The example lines leave out the double braces on purpose: Jinja (and so Salt)
# renders an expression tag even inside a # comment.


#------------------------------------------------------------------------------
# Serializers (SerializerExtension)
#------------------------------------------------------------------------------

# yaml -- flow style by default
#   {'a': [1, 2]} | yaml
#   -> {a: [1, 2]}
filters.yaml:
  test.nop:
    - result: {{ ({'a': [1, 2]} | yaml) | tojson }}

# json -- keys sorted
#   {'b': 1, 'a': 2} | json
#   -> {"a": 2, "b": 1}
filters.json:
  test.nop:
    - result: {{ ({'b': 1, 'a': 2} | json) | tojson }}

# load_yaml -- parses YAML text
#   'a: [1, 2]' | load_yaml
#   -> {'a': [1, 2]}
filters.load_yaml:
  test.nop:
    - result: {{ ('a: [1, 2]' | load_yaml) | tojson }}

# load_json -- parses JSON text
#   '{"a": 1}' | load_json
#   -> {'a': 1}
filters.load_json:
  test.nop:
    - result: {{ ('{"a": 1}' | load_json) | tojson }}

# load_text -- text as-is
#   'plain' | load_text
#   -> plain
filters.load_text:
  test.nop:
    - result: {{ ('plain' | load_text) | tojson }}


#------------------------------------------------------------------------------
# Lists, sets and sequences (salt/utils/jinja.py, data.py)
#------------------------------------------------------------------------------

# unique
#   ['a', 'b', 'a'] | unique
#   -> ['a', 'b']
filters.unique:
  test.nop:
    - result: {{ (['a', 'b', 'a'] | unique) | tojson }}

# min
#   [3, 1, 2] | min
#   -> 1
filters.min:
  test.nop:
    - result: {{ ([3, 1, 2] | min) | tojson }}

# max
#   [3, 1, 2] | max
#   -> 3
filters.max:
  test.nop:
    - result: {{ ([3, 1, 2] | max) | tojson }}

# avg -- always a float
#   [1, 2, 3, 4] | avg
#   -> 2.5
filters.avg:
  test.nop:
    - result: {{ ([1, 2, 3, 4] | avg) | tojson }}

# union
#   [1, 2, 3, 4] | union([2, 4, 6])
#   -> [1, 2, 3, 4, 6]
filters.union:
  test.nop:
    - result: {{ ([1, 2, 3, 4] | union([2, 4, 6])) | tojson }}

# intersect
#   [1, 2, 3, 4] | intersect([2, 4, 6])
#   -> [2, 4]
filters.intersect:
  test.nop:
    - result: {{ ([1, 2, 3, 4] | intersect([2, 4, 6])) | tojson }}

# difference
#   [1, 2, 3, 4] | difference([2, 4, 6])
#   -> [1, 3]
filters.difference:
  test.nop:
    - result: {{ ([1, 2, 3, 4] | difference([2, 4, 6])) | tojson }}

# symmetric_difference
#   [1, 2, 3, 4] | symmetric_difference([2, 4, 6])
#   -> [1, 3, 6]
filters.symmetric_difference:
  test.nop:
    - result: {{ ([1, 2, 3, 4] | symmetric_difference([2, 4, 6])) | tojson }}

# sequence -- wraps a non-list
#   'item' | sequence
#   -> ['item']
filters.sequence:
  test.nop:
    - result: {{ ('item' | sequence) | tojson }}

# skip -- always empty
#   'hidden' | skip
#   -> 
filters.skip:
  test.nop:
    - result: {{ ('hidden' | skip) | tojson }}

# flatten -- drops None / 'null' unless preserve_nulls=True
#   [1, [2, [3, None]], 'null'] | flatten
#   -> [1, 2, 3]
filters.flatten:
  test.nop:
    - result: {{ ([1, [2, [3, None]], 'null'] | flatten) | tojson }}

# is_iter -- strings don't count
#   [1, 2] | is_iter
#   -> True
filters.is_iter:
  test.nop:
    - result: {{ ([1, 2] | is_iter) | tojson }}

# is_list
#   [1, 2] | is_list
#   -> True
filters.is_list:
  test.nop:
    - result: {{ ([1, 2] | is_list) | tojson }}

# sorted_ignorecase
#   ['b', 'A', 'c'] | sorted_ignorecase
#   -> ['A', 'b', 'c']
filters.sorted_ignorecase:
  test.nop:
    - result: {{ (['b', 'A', 'c'] | sorted_ignorecase) | tojson }}

# substring_in_list
#   'yz' | substring_in_list(['xyz', 'abc'])
#   -> True
filters.substring_in_list:
  test.nop:
    - result: {{ ('yz' | substring_in_list(['xyz', 'abc'])) | tojson }}

# exactly_one_true
#   [True, False, False] | exactly_one_true
#   -> True
filters.exactly_one_true:
  test.nop:
    - result: {{ ([True, False, False] | exactly_one_true) | tojson }}

# exactly_n_true
#   [True, False, True] | exactly_n_true(2)
#   -> True
filters.exactly_n_true:
  test.nop:
    - result: {{ ([True, False, True] | exactly_n_true(2)) | tojson }}

# compare_lists -- old, new
#   [1, 2, 3] | compare_lists([2, 3, 4])
#   -> {'new': [4], 'old': [1]}
filters.compare_lists:
  test.nop:
    - result: {{ ([1, 2, 3] | compare_lists([2, 3, 4])) | tojson }}

# compare_dicts -- old, new
#   {'a': 1, 'b': 2} | compare_dicts({'a': 1, 'b': 3})
#   -> {'b': {'old': 2, 'new': 3}}
filters.compare_dicts:
  test.nop:
    - result: {{ ({'a': 1, 'b': 2} | compare_dicts({'a': 1, 'b': 3})) | tojson }}

# method_call -- calls str.split
#   'a,b,c' | method_call('split', ',')
#   -> ['a', 'b', 'c']
filters.method_call:
  test.nop:
    - result: {{ ('a,b,c' | method_call('split', ',')) | tojson }}


#------------------------------------------------------------------------------
# Dicts (salt/utils/data.py, dictupdate.py)
#------------------------------------------------------------------------------

# traverse -- colon-delimited path, through lists of dicts
#   {'a': {'b': [{'c': 1}]}} | traverse('a:b:c')
#   -> 1
filters.traverse:
  test.nop:
    - result: {{ ({'a': {'b': [{'c': 1}]}} | traverse('a:b:c')) | tojson }}

# set_dict_key_value
#   {} | set_dict_key_value('a:b', 1)
#   -> {'a': {'b': 1}}
filters.set_dict_key_value:
  test.nop:
    - result: {{ ({} | set_dict_key_value('a:b', 1)) | tojson }}

# update_dict_key_value
#   {'a': {'b': {'x': 1}}} | update_dict_key_value('a:b', {'y': 2})
#   -> {'a': {'b': {'x': 1, 'y': 2}}}
filters.update_dict_key_value:
  test.nop:
    - result: {{ ({'a': {'b': {'x': 1}}} | update_dict_key_value('a:b', {'y': 2})) | tojson }}

# append_dict_key_value
#   {'a': {'l': [1]}} | append_dict_key_value('a:l', 2)
#   -> {'a': {'l': [1, 2]}}
filters.append_dict_key_value:
  test.nop:
    - result: {{ ({'a': {'l': [1]}} | append_dict_key_value('a:l', 2)) | tojson }}

# extend_dict_key_value
#   {'a': [1]} | extend_dict_key_value('a', [2, 3])
#   -> {'a': [1, 2, 3]}
filters.extend_dict_key_value:
  test.nop:
    - result: {{ ({'a': [1]} | extend_dict_key_value('a', [2, 3])) | tojson }}

# to_entries -- 3007+ only -- not in 3006
#   {'a': 1, 'b': 2} | to_entries
#   -> [{'key': 'a', 'value': 1}, {'key': 'b', 'value': 2}]
filters.to_entries:
  test.nop:
    - result: {{ ({'a': 1, 'b': 2} | to_entries) | tojson }}

# from_entries -- 3007+ only -- not in 3006
#   [{'key': 'a', 'value': 1}] | from_entries
#   -> {'a': 1}
filters.from_entries:
  test.nop:
    - result: {{ ([{'key': 'a', 'value': 1}] | from_entries) | tojson }}


#------------------------------------------------------------------------------
# Strings, numbers, regex (salt/utils/stringutils.py, jinja.py)
#------------------------------------------------------------------------------

# to_bool -- 'yes'/'1'/'true' only -- 'on' is False
#   'yes' | to_bool
#   -> True
filters.to_bool:
  test.nop:
    - result: {{ ('yes' | to_bool) | tojson }}

# to_num
#   '42' | to_num
#   -> 42
filters.to_num:
  test.nop:
    - result: {{ ('42' | to_num) | tojson }}

# str_to_num -- alias of to_num
#   '4.2' | str_to_num
#   -> 4.2
filters.str_to_num:
  test.nop:
    - result: {{ ('4.2' | str_to_num) | tojson }}

# is_hex
#   'ff' | is_hex
#   -> True
filters.is_hex:
  test.nop:
    - result: {{ ('ff' | is_hex) | tojson }}

# contains_whitespace
#   'a b' | contains_whitespace
#   -> True
filters.contains_whitespace:
  test.nop:
    - result: {{ ('a b' | contains_whitespace) | tojson }}

# human_to_bytes
#   '2 KiB' | human_to_bytes
#   -> 2048
filters.human_to_bytes:
  test.nop:
    - result: {{ ('2 KiB' | human_to_bytes) | tojson }}

# to_camelcase
#   'snake_case_here' | to_camelcase
#   -> snakeCaseHere
filters.to_camelcase:
  test.nop:
    - result: {{ ('snake_case_here' | to_camelcase) | tojson }}

# to_snake_case
#   'camelCaseHere' | to_snake_case
#   -> camel_case_here
filters.to_snake_case:
  test.nop:
    - result: {{ ('camelCaseHere' | to_snake_case) | tojson }}

# check_whitelist_blacklist -- globs or regexes
#   'web01' | check_whitelist_blacklist(whitelist='web*')
#   -> True
filters.check_whitelist_blacklist:
  test.nop:
    - result: {{ ('web01' | check_whitelist_blacklist(whitelist='web*')) | tojson }}

# to_bytes
#   'abc' | to_bytes
#   -> b'abc'
filters.to_bytes:
  test.nop:
    - result: {{ ('abc' | to_bytes) | string | tojson }}

# quote -- shell quoting
#   "it's here" | quote
#   -> 'it'"'"'s here'
filters.quote:
  test.nop:
    - result: {{ ("it's here" | quote) | tojson }}

# regex_escape
#   'a.b*c' | regex_escape
#   -> a\.b\*c
filters.regex_escape:
  test.nop:
    - result: {{ ('a.b*c' | regex_escape) | tojson }}

# regex_search -- the groups
#   'abcd' | regex_search('^(.*)BC(.*)$', ignorecase=True)
#   -> ('a', 'd')
filters.regex_search:
  test.nop:
    - result: {{ ('abcd' | regex_search('^(.*)BC(.*)$', ignorecase=True)) | tojson }}

# regex_search -- no groups: 3006 gives (), 3007+ the whole match
#   'abcd' | regex_search('BC', ignorecase=True)
#   -> ('bc',)
filters.regex_search.no_groups:
  test.nop:
    - result: {{ ('abcd' | regex_search('BC', ignorecase=True)) | tojson }}

# regex_match -- the groups
#   'abcd' | regex_match('^(.*)BC(.*)$', ignorecase=True)
#   -> ('a', 'd')
filters.regex_match:
  test.nop:
    - result: {{ ('abcd' | regex_match('^(.*)BC(.*)$', ignorecase=True)) | tojson }}

# regex_match -- no groups: 3006 gives (), 3007+ the whole match
#   'abcd' | regex_match('ABC', ignorecase=True)
#   -> ('abc',)
filters.regex_match.no_groups:
  test.nop:
    - result: {{ ('abcd' | regex_match('ABC', ignorecase=True)) | tojson }}

# regex_replace
#   'lets replace spaces' | regex_replace('\\s+', '__')
#   -> lets__replace__spaces
filters.regex_replace:
  test.nop:
    - result: {{ ('lets replace spaces' | regex_replace('\\s+', '__')) | tojson }}

# indent -- Salt's own indent
#   'a\nb' | indent(2)
#   -> a\n  b
filters.indent:
  test.nop:
    - result: {{ ('a\nb' | indent(2)) | tojson }}

# tojson -- escapes < > & '
#   {'a': '<b>'} | tojson
#   -> {"a": "\u003cb\u003e"}
filters.tojson:
  test.nop:
    - result: {{ ({'a': '<b>'} | tojson) | tojson }}

# uuid -- deterministic: UUID5 of the value
#   'random' | uuid
#   -> 3652b285-26ad-588e-a5dc-c2ee65edc804
filters.uuid:
  test.nop:
    - result: {{ ('random' | uuid) | tojson }}


#------------------------------------------------------------------------------
# Hashing and encoding (salt/utils/hashutils.py)
#------------------------------------------------------------------------------

# base64_encode
#   'hello' | base64_encode
#   -> aGVsbG8=
filters.base64_encode:
  test.nop:
    - result: {{ ('hello' | base64_encode) | tojson }}

# base64_decode
#   'aGVsbG8=' | base64_decode
#   -> hello
filters.base64_decode:
  test.nop:
    - result: {{ ('aGVsbG8=' | base64_decode) | tojson }}

# md5
#   'hello' | md5
#   -> 5d41402abc4b2a76b9719d911017c592
filters.md5:
  test.nop:
    - result: {{ ('hello' | md5) | tojson }}

# sha1
#   'hello' | sha1
#   -> aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d
filters.sha1:
  test.nop:
    - result: {{ ('hello' | sha1) | tojson }}

# sha256
#   'hello' | sha256
#   -> 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
filters.sha256:
  test.nop:
    - result: {{ ('hello' | sha256) | tojson }}

# sha512
#   'hello' | sha512
#   -> 9b71d224bd62f3785d96d46ad3ea3d73319bfbc2890caadae2dff72519673ca72323c3d99ba5c11d7c7acc6e14b8c5da0c4663475c2e5c3adef46f73bcdec043
filters.sha512:
  test.nop:
    - result: {{ ('hello' | sha512) | tojson }}

# hmac_compute -- hex SHA-256 HMAC
#   'message' | hmac_compute('secret')
#   -> 8b5f48702995c1598c573db1e21866a9b825d4a794d169d7060a03605796360b
filters.hmac_compute:
  test.nop:
    - result: {{ ('message' | hmac_compute('secret')) | tojson }}

# hmac -- checks a base64 HMAC
#   'message' | hmac('secret', 'wrong')
#   -> False
filters.hmac:
  test.nop:
    - result: {{ ('message' | hmac('secret', 'wrong')) | tojson }}


#------------------------------------------------------------------------------
# Paths and YAML quoting (salt/utils/path.py, yamlencoding.py)
#------------------------------------------------------------------------------

# path_join
#   '/etc' | path_join('salt', 'minion')
#   -> /etc/salt/minion
filters.path_join:
  test.nop:
    - result: {{ ('/etc' | path_join('salt', 'minion')) | tojson }}

# yaml_dquote
#   'say "hi"' | yaml_dquote
#   -> "say \"hi\""
filters.yaml_dquote:
  test.nop:
    - result: {{ ('say "hi"' | yaml_dquote) | tojson }}

# yaml_squote
#   "it's" | yaml_squote
#   -> 'it''s'
filters.yaml_squote:
  test.nop:
    - result: {{ ("it's" | yaml_squote) | tojson }}

# yaml_encode
#   'text' | yaml_encode
#   -> "text"
filters.yaml_encode:
  test.nop:
    - result: {{ ('text' | yaml_encode) | tojson }}


#------------------------------------------------------------------------------
# Environment-dependent filters: their result depends on the minion (DNS, HTTP,
# files, users), on randomness or the current time, or on the networking helpers'
# option modes -- so the preview asks for each one in the Salt Preview panel
# ("Environment-dependent filters") instead of guessing. Unanswered, each renders
# as a filter:... placeholder in guillemets; printed double-quoted (not tojson) so it and your answer
# show exactly as Jinja prints them.
#------------------------------------------------------------------------------

# dns_check
#   'localhost' | dns_check(80)
filters.dns_check:
  test.nop:
    - result: "{{ 'localhost' | dns_check(80) }}"

# http_query
#   'https://example.com' | http_query
filters.http_query:
  test.nop:
    - result: "{{ 'https://example.com' | http_query }}"

# which
#   'bash' | which
filters.which:
  test.nop:
    - result: "{{ 'bash' | which }}"

# file_hashsum
#   '/etc/hosts' | file_hashsum
filters.file_hashsum:
  test.nop:
    - result: "{{ '/etc/hosts' | file_hashsum }}"

# get_uid
#   'root' | get_uid
filters.get_uid:
  test.nop:
    - result: "{{ 'root' | get_uid }}"

# list_files
#   '/etc/salt' | list_files
filters.list_files:
  test.nop:
    - result: "{{ '/etc/salt' | list_files }}"

# is_bin_file
#   '/bin/ls' | is_bin_file
filters.is_bin_file:
  test.nop:
    - result: "{{ '/bin/ls' | is_bin_file }}"

# is_text_file
#   '/etc/hosts' | is_text_file
filters.is_text_file:
  test.nop:
    - result: "{{ '/etc/hosts' | is_text_file }}"

# is_empty
#   '/etc/hosts' | is_empty
filters.is_empty:
  test.nop:
    - result: "{{ '/etc/hosts' | is_empty }}"

# random_hash
#   32 | random_hash
filters.random_hash:
  test.nop:
    - result: "{{ 32 | random_hash }}"

# rand_str
#   32 | rand_str
filters.rand_str:
  test.nop:
    - result: "{{ 32 | rand_str }}"

# random_str
#   16 | random_str
filters.random_str:
  test.nop:
    - result: "{{ 16 | random_str }}"

# random_sample
#   [1, 2, 3] | random_sample(2)
filters.random_sample:
  test.nop:
    - result: "{{ [1, 2, 3] | random_sample(2) }}"

# random_shuffle
#   [1, 2, 3] | random_shuffle
filters.random_shuffle:
  test.nop:
    - result: "{{ [1, 2, 3] | random_shuffle }}"

# gen_mac
#   'AC:DE:48' | gen_mac
filters.gen_mac:
  test.nop:
    - result: "{{ 'AC:DE:48' | gen_mac }}"

# strftime
#   '2002/12/25' | strftime('%y')
filters.strftime:
  test.nop:
    - result: "{{ '2002/12/25' | strftime('%y') }}"

# date_format
#   '2002/12/25' | date_format
filters.date_format:
  test.nop:
    - result: "{{ '2002/12/25' | date_format }}"

# ipaddr
#   ['192.168.0.1', 'foo'] | ipaddr
filters.ipaddr:
  test.nop:
    - result: "{{ ['192.168.0.1', 'foo'] | ipaddr }}"

# ipv4
#   '192.168.0.1' | ipv4
filters.ipv4:
  test.nop:
    - result: "{{ '192.168.0.1' | ipv4 }}"

# ipv6
#   '::1' | ipv6
filters.ipv6:
  test.nop:
    - result: "{{ '::1' | ipv6 }}"

# ip_host
#   '192.168.0.1/24' | ip_host
filters.ip_host:
  test.nop:
    - result: "{{ '192.168.0.1/24' | ip_host }}"

# is_ip
#   '192.168.0.1' | is_ip
filters.is_ip:
  test.nop:
    - result: "{{ '192.168.0.1' | is_ip }}"

# is_ipv4
#   '192.168.0.1' | is_ipv4
filters.is_ipv4:
  test.nop:
    - result: "{{ '192.168.0.1' | is_ipv4 }}"

# is_ipv6
#   '::1' | is_ipv6
filters.is_ipv6:
  test.nop:
    - result: "{{ '::1' | is_ipv6 }}"

# ipwrap
#   '::1' | ipwrap
filters.ipwrap:
  test.nop:
    - result: "{{ '::1' | ipwrap }}"

# network_hosts
#   '192.168.0.0/30' | network_hosts
filters.network_hosts:
  test.nop:
    - result: "{{ '192.168.0.0/30' | network_hosts }}"

# network_size
#   '192.168.0.0/24' | network_size
filters.network_size:
  test.nop:
    - result: "{{ '192.168.0.0/24' | network_size }}"

# filter_by_networks
#   ['10.0.0.1'] | filter_by_networks(['10.0.0.0/8'])
filters.filter_by_networks:
  test.nop:
    - result: "{{ ['10.0.0.1'] | filter_by_networks(['10.0.0.0/8']) }}"

# mac_str_to_bytes
#   'f5:00:00:00:00:00' | mac_str_to_bytes
filters.mac_str_to_bytes:
  test.nop:
    - result: "{{ 'f5:00:00:00:00:00' | mac_str_to_bytes }}"

# json_query
#   {'a': [1, 2]} | json_query('a[0]')
filters.json_query:
  test.nop:
    - result: "{{ {'a': [1, 2]} | json_query('a[0]') }}"

# mysql_to_dict
#   '' | mysql_to_dict('Id')
filters.mysql_to_dict:
  test.nop:
    - result: "{{ '' | mysql_to_dict('Id') }}"

# json_encode_dict
#   {'a': 'b'} | json_encode_dict
filters.json_encode_dict:
  test.nop:
    - result: "{{ {'a': 'b'} | json_encode_dict }}"

# json_encode_list
#   ['a'] | json_encode_list
filters.json_encode_list:
  test.nop:
    - result: "{{ ['a'] | json_encode_list }}"

# json_decode_dict
#   {'a': 'b'} | json_decode_dict
filters.json_decode_dict:
  test.nop:
    - result: "{{ {'a': 'b'} | json_decode_dict }}"

# json_decode_list
#   ['a'] | json_decode_list
filters.json_decode_list:
  test.nop:
    - result: "{{ ['a'] | json_decode_list }}"
